language: python
python:
  - "3.7"

sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    - sourceline: 'deb http://packages.prosody.im/debian trusty main'
      key_url: 'https://prosody.im/files/prosody-debian-packages.key'
    packages:
    - curl
    - mosquitto
    - zookeeperd
    - prosody-0.10
    - lua-bitop
    - lua-sec
    - openjdk-8-jre-headless

services:
  - mosquitto
  - redis-server
  - zookeeper
  - prosody

env:
  global:
    - COVERAGE_PROCESS_START=".coveragerc"
    - KARAF_DIR=/tmp

install:
  - sudo prosodyctl register user1 localhost foobar
  - sudo prosodyctl register user2 localhost foobar
  - sudo prosodyctl restart
  - curl -qL http://mirrors.ircam.fr/pub/apache/karaf/4.2.7/apache-karaf-4.2.7.tar.gz | tar xz -C /tmp
  - curl -qL https://github.com/etcd-io/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz | tar xz -C /tmp && /tmp/etcd-v3.3.10-linux-amd64/etcd &
  - pip install nose coverage coverage_enable_subprocess coveralls
  - pip install https://github.com/tcalmant/jsonrpclib/archive/master.zip
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=pelix tests

after_success:
  - coveralls
